- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ check --fix docs/ hooks/ tests/]
    # Run the formatter.
    - id: ruff
      args: [ format docs/ hooks/ tests/ ] 

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''  # Use the sha / tag you want to point at
  hooks:
  -   id: mypy
      args: [ hooks/ tests/ ]