name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  code-quality:
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Code Quality
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {{ "${{ matrix.python-version }}" }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Configure Poetry
        run: |
          poetry config cache-dir "${GITHUB_WORKSPACE}/.cache/pypoetry"
          poetry config virtualenvs.in-project true

      - name: Run formatter
        run: |
          poetry run tox -e formatter

      - name: Run linter
        run: |
          poetry run tox -e linter

      - name: Run typer
        run: |
          poetry run tox -e typer

  documentation:
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Documentation
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {{ "${{ matrix.python-version }}" }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Configure Poetry
        run: |
          poetry config cache-dir "${GITHUB_WORKSPACE}/.cache/pypoetry"
          poetry config virtualenvs.in-project true

      - name: Run documentation
        run: |
          poetry run tox -e documentation