name: linters

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  linters:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: ["3.10"]
        include:
          - os: Ubuntu
            image: ubuntu-22.04
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: poetry install -E doc -E tests

      - name: Run black
        run: poetry run tox -e black

      - name : Run flake8 
        run : poetry run tox -e flake8

      - name : Run mypy 
        run : poetry run tox -e mypy

      - name : Run doc8 
        run : poetry run tox -e doc8



