name: on_pull_request

on:
  pull_request:
    branches: 
      - 'main'

jobs:
  pull_request:
    name: pull_request
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        id: install-poetry
        run: python -m pip install poetry

      - name: Configure poetry
        id: configure-poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install -E doc -E tests

      - name: Run linters
        run: poetry run tox -e linters
          
      - name: Run tests
        run: poetry run tox -e py310

      - name: Build documentation
        run: poetry run tox -e docs
