name: main

on:
  push:
    branches: 
      - '**'
    tags:        
      - 'v*'

jobs:
  tag:
    name: tag
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        id: install-poetry
        run: python -m pip install poetry

      - name: Configure poetry
        id: configure-poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install -E doc -E tests

      - name: Run linters
        run: poetry run tox -e linters
          
      - name: Run tests
        run: poetry run tox -e py310

      - name: code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      - name: Build documentation
        run: poetry run tox -e docs

      # - name: Setup Pages
      #   uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # - name: Archive documentation
      #   run: |
      #     tar \
      #       --dereference --hard-dereference \
      #       --directory "docs/build/html" \
      #       -cvf "$RUNNER_TEMP/documentation.tar" \
      #       .

      # - name: Upload documentation artifact
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: github-pages
      #     path: ${{ runner.temp }}/documentation.tar
      #     retention-days: 1

      # - name: Upload documentation to GitHub Pages
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "    